config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'

  #About page
  get 'about', to: 'pages#about'

  #Articles
  resources :articles

  #User
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #Searching
  get 'search', to: 'searches#search_articles'

  #Categories
  resources :categories

  #Identifications
  get 'ident', to: 'pages#identification'
  get 'user_ident/:id', to: 'identifications#user_ident',as: "user_ident" 
  resources :identifications, except: [:index, :show]
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories, dependent: :destroy
    has_many :categories, through: :article_categories
    validates :title, presence: true, 
                      length: { minimum: 5 ,maximum: 50}
    validates :description, presence: true, 
                            length: { minimum: 10 ,maximum: 100}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user

    def show
        
    end

    def index
        @articles=Article.paginate(page: params[:page], per_page: 2)
    end

    def new
        @article=Article.new
    end

    def edit
        
    end

    def create
        @article=Article.new(article_params)
        @article.user=current_user
        if @article.save
            flash[:notice]="Article save succesfully"
            redirect_to article_path(@article)
        else
            render 'new' , status: 422
        end
    end

    def update 
        if @article.update(article_params)
            flash[:notice]="Article update succesfully"
            redirect_to article_path(@article)
        else
            render 'edit', status: 422
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private
    
    def set_article
        @article=Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to articles_path
        end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<div class="container text-center">
  <% obj.each do |article| %>
    <div class="container card-box">
      <div class="container card-item">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            <%= link_to "by #{article.user.username}", user_path(article.user), class: "user-article-link" %>
            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %></div> 
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success text-decoration-none" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && current_user.admin? %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-primary" %>
              <%= link_to 'Delete', article_path(article),class: "btn btn-outline-danger", data: {"turbo-method": :delete, "turbo-confirm":"are you sure ?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <span>Created <%= time_ago_in_words(article.created_at) %> ago</span>
            <span>Edited <%= time_ago_in_words(article.updated_at) %> ago</span> 
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container pt-4 text-white form-box">
  <%= form_with(model:@article, local: true) do |f| %>
        <div class="row mb-4">
          <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2"><%= f.label :title, class: "form-label" %></div>
          <div class="col-xs-12 col-sm-10 12 col-md-10 col-lg-10 col-xl-10"><%= f.text_field :title, placeholder: "Title text", class: "form-control" %></div>
        </div>
        <div class="row mb-4">
          <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2"><%= f.label :description, class: "form-label" %></div>
          <div class="col-xs-12 col-sm-10 12 col-md-10 col-lg-10 col-xl-10"><%= f.text_area :description, placeholder: "Description text", class: "form-control", size: "40x10" %></div>
        </div>
        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
          </div>
        </div>
        <p class="text-center mt-3">
          <%= f.submit class:"btn-article" %> 
        </p>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit article</h1>
<%= render "shared/errors", obj: @article %>
<%= render "form"%>
<div class="text-center mt-4">
    <%= link_to 'Return to Articles listing', articles_path, class:"btn btn-outline-primary" %>
</div>

app/views/articles/index.html.erb
<div class="container text-center">
  <h1 id="articles-index-title">Articles listing page</h1>
</div>
<div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles', obj: @articles%>
<div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
    <h1 class="text-center">Create a new article</h1>
    <%= render "shared/errors", obj: @article %>
    <%= render "form"%>
    <div class="text-center mt-4">
        <%= link_to 'Return to Articles listing', articles_path, class:"btn btn-outline-primary" %>
    </div>
    

app/views/articles/show.html.erb
<div class="container text-center">
    <h2 id="article-index-title"><%= @article.title %></h2>
    <div class="container card-box">
      <div class="container card-item">
        <div class="card shadow mb-5 bg-white rounded">
          <div class="card-header">
            <%= link_to "by #{@article.user.username}", user_path(@article.user), class: "user-article-link" %>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            <% if @article.categories.any? %>
              <div class="mt-2"><span><%= render @article.categories %></div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to @article.title, article_path(@article), class: "text-success text-decoration-none" %></h5>
            <p class="card-text card-text-show"><%= simple_format(@article.description) %></p>
            <% if logged_in? && current_user.admin? %>
              <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-primary" %>
              <%= link_to 'Delete', article_path(@article),class: "btn btn-outline-danger", data: {"turbo-method": :delete, "turbo-confirm":"are you sure ?"} %>
            <% end%>
          </div>
          <div class="card-footer text-muted">
            <span>Created <%= time_ago_in_words(@article.created_at) %> ago</span>
            <span>Edited <%= time_ago_in_words(@article.updated_at) %> ago</span> 
          </div>
        </div>
      </div>
    </div>
</div>
<div class="text-center mt-4">
    <%= link_to 'Return to Articles listing', articles_path, class:"btn btn-outline-primary" %>
</div>