config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'

  #About page
  get 'about', to: 'pages#about'

  #Articles
  resources :articles

  #User
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #Searching
  get 'search', to: 'searches#search_articles'

  #Categories
  resources :categories

  #Identifications
  get 'ident', to: 'pages#identification'
  get 'user_ident/:id', to: 'identifications#user_ident',as: "user_ident" 
  resources :identifications, except: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    has_one :identification, dependent: :destroy
    validates :username, presence: true,
                         uniqueness: {case_sensitive: false},
                         length: {minimum: 3 , maximum: 50}

    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                      uniqueness: {case_sensitive: false},
                      length: {maximum: 100},
                      format: { with: VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user

    def show
        @user_articles=@user.articles.paginate(page: params[:page], per_page: 2)
    end
    
    def index
        @users=User.paginate(page: params[:page], per_page: 2)
    end

    def new
        @user=User.new
    end

    def edit
        
    end

    def create
        @user=User.new(user_params)
        if @user.save
            flash[:notice]= "Welcome to Captain blog #{@user.username}"
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'new' , status: 422
        end
    end

    def update
        if @user.update(user_params)
            flash[:notice]="#{@user.username} update succesfully"
            redirect_to user_path
        else
            render 'edit', status: 422
        end
    end

    def destroy
        @user.destroy
        flash[:notice]="User deleted with success"
        session[:user_id]=nil if current_user == @user
        redirect_to users_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :admin ,:password, :password_confirmation)
    end

    def set_user
        @user=User.find(params[:id])
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to users_path
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end
end

app/views/users/_form.html.erb
<div class="container pt-4 text-white form-box">
  <%= form_with(model:@user, local: true) do |f| %>
        <div class="row mb-4">
          <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2"><%= f.label :username,"User name" ,class: "form-label" %></div>
          <div class="col-xs-12 col-sm-10 12 col-md-10 col-lg-10 col-xl-10"><%= f.text_field :username, placeholder: "Enter a user name", class: "form-control" %></div>
        </div>
        <div class="row mb-4">
          <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2"><%= f.label :email, class: "form-label" %></div>
          <div class="col-xs-12 col-sm-10 12 col-md-10 col-lg-10 col-xl-10"><%= f.email_field :email, placeholder: "Enter a email", class: "form-control" %></div>
        </div>
        <div class="row mb-4">
          <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2"><%= f.label :admin ,"Admin",class: "form-label" %></div>
          <div class="col-xs-12 col-sm-10 12 col-md-10 col-lg-10 col-xl-10">
            <%= f.radio_button :admin, true %>
          </div>
          <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2"><%= f.label :admin,"Not admin" ,class: "form-label" %></div>
          <div class="col-xs-12 col-sm-10 12 col-md-10 col-lg-10 col-xl-10">
            <%= f.radio_button :admin, false %>
          </div>
        </div>
        <div class="row mb-4">
          <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2"><%= f.label :password, class: "form-label" %></div>
          <div class="col-xs-12 col-sm-10 12 col-md-10 col-lg-10 col-xl-10"><%= f.password_field :password, placeholder: "Enter a password", class: "form-control" %></div>
        </div>
        <div class="row mb-4">
          <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2"><%= f.label :password_confirmation, class: "form-label" %></div>
          <div class="col-xs-12 col-sm-10 12 col-md-10 col-lg-10 col-xl-10"><%= f.password_field :password_confirmation, placeholder: "Enter the same password", class: "form-control" %></div>
        </div>
        <p class="text-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class:"btn-article") %> 
        </p>
  <% end %>
</div>

app/views/users/edit.html.erb
    <h1 class="text-center">Edit <%= @user.username %>'s profile </h1>
    <%= render "shared/errors", obj: @user %>
    <%= render "form"%>
    <!--<div class="text-center mt-4">
        <%= link_to 'Return to Articles listing', articles_path, class:"btn btn-outline-primary" %>
    </div>
    

app/views/users/index.html.erb
<div class="container text-center">
  <h1 id="users-index-title">Captain Bloggers</h1>
</div>
<div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
</div>

<div class="container text-center">
  <% @users.each do |user| %>
    <div class="container card-box">
      <div class="container card-item">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            <%= link_to user.username, user_path(user), class: "user-article-link" %>
          </div>
          <div class="card-body">
            <p class="card-text"><%= gravatar_for(user, size: 150) %></p>
            <p> <%= pluralize(user.articles.count, 'article') %> </p>
            <%= link_to 'View profile', user_path(user), class: "btn btn-outline-success" %>
            <% if logged_in?%>
              <% if current_user.admin? && current_user == user %>
                <%= link_to 'Edit your profile', edit_user_path(current_user), class: "btn btn-outline-primary" %>
                <%= link_to "Delete your profile", user_path(current_user), class:"btn btn-outline-danger", data: {"turbo-method": :delete, "turbo-confirm":"are you sure ?"} %>
              <% elsif current_user.admin?  %>
                <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-primary" %>
                <%= link_to "Delete profile", user_path(user), class:"btn btn-outline-danger", data: {"turbo-method": :delete, "turbo-confirm":"are you sure ?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <span>Join <%= time_ago_in_words(user.created_at) %> ago</span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
    <h1 class="text-center">Sign up for Captain Blog</h1>
    <%= render "shared/errors", obj: @user %>
    <%= render "form"%>
    

app/views/users/show.html.erb
<div class="contaner text-center">
  <h1 class="text-center"><%= @user.username %>'s profile </h1>
  <%= gravatar_for @user, size: 200 %>
  <% if logged_in? && current_user.admin? %>
    <%= link_to 'Edit user profile', edit_user_path(@user), class: "btn btn-outline-primary mt-3" %>
    <%= link_to 'Delete user profile', user_path(@user),class: "btn btn-outline-danger mt-3", data: {"turbo-method": :delete, "turbo-confirm":"are you sure ?"} %>
  <% end %>
  <div class="mt-3">
      <%= link_to 'User ID table', ident_path, class: "btn btn-outline-primary mt-3" %>
  </div>
   <% if @user_articles.count != 0 %>
  <div class="container text-center mt-4">
    <h1>Articles of <%= @user.username %> </h1>
  </div>
    <div class="flickr_pagination mb-4">
      <div class="page_info">
        <%= page_entries_info @user_articles %>
      </div>
      <%= will_paginate @user_articles, :container => false %>
    </div>
  
    <%= render 'articles/articles', obj: @user_articles%>
    <div class="flickr_pagination mb-4">
      <div class="page_info">
        <%= page_entries_info @user_articles %>
      </div>
      <%= will_paginate @user_articles, :container => false %>
    </div>
  <% end %>
</div>