config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'

  #About page
  get 'about', to: 'pages#about'

  #Articles
  resources :articles

  #User
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #Searching
  get 'search', to: 'searches#search_articles'

  #Categories
  resources :categories

  #Identifications
  get 'ident', to: 'pages#identification'
  get 'user_ident/:id', to: 'identifications#user_ident',as: "user_ident" 
  resources :identifications, except: [:index, :show]
end

app/views/pages/about.html.erb
<!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container">

        <div class="section-title">
          <h2>About</h2>
          <h5> Georges is in charge of maintaining this website. </h5>
        </div>

        <div class="row">
          <div class="col-lg-4" data-aos="fade-right">
            <%= image_tag("main-brand.jpg",class: "img-fluid" ,alt: "Picture of the CEO", height: "50px") %>
          </div>
          <div class="col-8 col-md-8 col-lg-8 col-xl-8 col-xxl-8">
                <section class="second-frame skills">
                    <p>My speciality</p>
                    <h1 id="second-title">My Skills</h1>
                    <div class="row">
                        <div class="col-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
                            <div class="skill-name">
                                <p>HTML5 & CSS3</p>
                                <div class="progress">
                                    <div class="progress-bar bg-secondary" role="progressbar" style="width: 85%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>   
                            <div class="skill-name">
                                <p>Bootstrap</p>
                                <div class="progress">
                                    <div class="progress-bar bg-secondary" role="progressbar" style="width: 75%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                            <div class="skill-name">
                                <p>JavaScript</p>
                                <div class="progress">
                                    <div class="progress-bar bg-secondary" role="progressbar" style="width: 70%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                            <div class="skill-name">
                                <p>VueJs</p>
                                <div class="progress">
                                    <div class="progress-bar bg-secondary" role="progressbar" style="width: 60%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
                            <div class="skill-name">
                                <p>Ruby</p>
                                <div class="progress">
                                    <div class="progress-bar bg-secondary" role="progressbar" style="width: 55%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                            <div class="skill-name">
                                <p>Rails & Sinatra</p>
                                <div class="progress">
                                    <div class="progress-bar bg-secondary" role="progressbar" style="width: 45%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                            <div class="skill-name">
                                <p>SQL</p>
                                <div class="progress">
                                    <div class="progress-bar bg-secondary" role="progressbar" style="width: 65%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                            <div class="skill-name">
                                <p>MySql & Postgresql</p>
                                <div class="progress">
                                    <div class="progress-bar bg-secondary" role="progressbar" style="width: 60%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                                
                        </div>     
                    </div>
                    <p>We know when we get started but not when We'll stop, let's bounce....</p>
                    <span>
                        Learning: <strong>PHP, </strong>
                    </span>
                    <span>
                        <strong>Laravel </strong>
                    </span>
                    <span>
                        <strong>& ReactJs</strong>
                    </span>
                </section>
            </div>
        </div>

        </div>
    </section><!-- End About Section -->

app/views/pages/home.html.erb
<div class="container-fluid home-main">
    <div class="jumbotron">
        <h1>Welcome to Captain blog</h1>
        <p>
           This site is under the responsibility of <a href="/about" class="georges-link">Georges</a>.
           <p>
            Please contact <a href="/about" class="georges-link">Georges</a> to full acces in our publications.
           </p>
        </p>
    </div>
    
</div>

app/views/pages/identification.html.erb
<h1 class="text-center mb-3">Identification table </h1>
<div class="container">
    <table class="table table-striped border">
        <thead>
            <tr>
            <th scope="col">User Name</th>
            <th scope="col">Register number</th>
            <th scope="col">User active</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
                <tr>
                    <th scope="row"><%= user.username%></th>
                    <% if !user.identification.nil? %>
                        <td> <%= user.identification.register_number %> </td>
                        <td><%= user.identification.active %></td>
                        <td>
                            <%= link_to 'Edit RN', edit_identification_path(user.identification), class: "btn btn-outline-primary m-2" %>
                            <%= link_to 'Delete RN', identification_path(user.identification),class: "btn btn-outline-danger", data: {"turbo-method": :delete, "turbo-confirm":"are you sure ?"} %>
                        </td>
                    <% else %>
                        <td> No number </td>
                        <td> nil</td>
                        <td>
                            <%= link_to 'Assign RN', user_ident_path(id: user), class: "btn btn-outline-success" %>
                        </td>
                    <% end %>
                    
                </tr>
            <% end %>
        </tbody>
    </table>
</div>