config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'

  #About page
  get 'about', to: 'pages#about'

  #Articles
  resources :articles

  #User
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #Searching
  get 'search', to: 'searches#search_articles'

  #Categories
  resources :categories

  #Identifications
  get 'ident', to: 'pages#identification'
  get 'user_ident/:id', to: 'identifications#user_ident',as: "user_ident" 
  resources :identifications, except: [:index, :show]
end

app/views/layouts/_footer.html.erb
<div id="page-content">
</div>
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center mt-4">
        <article id="roche-pub">
            <h3 class="text-white">My extension Program</h3>
            <iframe height="184" src="https://www.youtube.com/embed/dekPu8gGmSQ" title="Caminhos do SUS: Direito e Acesso à Saúde para Migrantes." frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </article>
    </div>
    <div class="container text-center">
        <small>Copyright &copy; Captain blog</small>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to image_tag("main-brand.jpg",class: "main-brand" ,alt: "Picture of the CEO", height: "50px"), root_path %>
    <%= link_to "CAPTAIN", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>  
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "New article", new_article_path, class:"dropdown-item" %></li>
            <li><%= link_to "All articles", articles_path, class:"dropdown-item" %></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "New Category", new_category_path, class:"dropdown-item" %></li>
            <li><%= link_to "All Categories", categories_path, class:"dropdown-item" %></li>
          </ul>
        </li>
        
        <% if logged_in? %>
          <li class="nav-item">
           <%= link_to gravatar_for(current_user, size: 30), user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "View your profile", user_path(current_user), class:"dropdown-item" %></li>
              <% if current_user.admin? %>
                <li><%= link_to "Edit your profile", edit_user_path(current_user), class:"dropdown-item" %></li>
                <li><%= link_to "Delete your profile", user_path(current_user), class:"dropdown-item text-danger", data: {"turbo-method": :delete, "turbo-confirm":"are you sure ?"} %></li>
              <% end %>
            </ul>
          </li>
          <li class="nav-item">
           <%= link_to "Log out", logout_path, class: "nav-link", 'data-turbo-method': :delete%>
          </li>
        <% else %>
          <li class="nav-item">
           <%= link_to "Sign in", login_path, class: "nav-link"%>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Create user", signup_path, class: "nav-link"%>
        </li>
        
      </ul>
      <%= form_with url: "/search", class:"d-flex", method: :get do |form| %>
        <%= form.label :query, "Search for:" %>
        <%= form.text_field :query, class:"form-control me-2", placeholder:"Search for an article" %>
        <%= form.submit "Search", class:"btn btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <div class="header">
      <%= render "layouts/header"%>
    </div>
    
    <% flash.each do |name,msg|%>
      <div class="container alert alert-<%= name=='notice' ? 'success': 'danger' %>" role="alert">
        <p><%= msg %></p>
      </div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer"%>
  </body>
</html>